# Generated by Django 4.1.5 on 2023-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
